sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: IrNq/HRWh9q7esnUuv91FPkMhccyOyBFRJjaImrHxN8PeL+4u6oV3UA7YIvwZzjh6D1orJNamcQ969VQfwB8UCGQGtI4/154CndEE1GPzlvziYTeXPZZiJAV2hgK3pPwJ3KFAbxAGLHjNU1/Yd99uSCxJ7Ebvh+S1nHtu2p3vNDzO5WOxnhws3Q4lQNKUk2enAaQYefmsbBOkTDDTpbE1gIPHmdf+1OLGqoU9xPgxRAAUgg1O1AzwXeKTBI0PcoK1QcFHrMTOkuAARmtpwzBTd5nL2n6X2xkNn7WUnaUvjqsC2TOiic6AgAamarM4ezg535eLsdN9J/4s3cHgBpDGjEx60wURFpbxA5+GNWeyzQC0SleeptF74RzcwAKfQJITmOrCf1sOxy15uGEU1/ALqSNUa4rmeransFgzwpU6mrHrdY4kmWHcoMtjAQMtfOuO6dZuw95vgxHPC4ss1BETkDXijj/n2ANiHhdIxou3nUB4q9MMlXcCOGYk97hc7eJfkmcI2UjKgmA3jxQ/NsZQkXkINZiPsJstrHhbeCne7/ImA2T0qdd4AxkNn0Dz7w3P/nhfNW1SIaYBPqG5D3/DgCEtCiv7D1+N5iAy4G84KsU16g+5BE4pqqDVhuNeInlojQq+DVAJFShEBxjB4Cj7TpGdpWSN+5/MHwin0elv7E=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: mSfi4zavnk2PfMbqtxn3lZunYvRs1CMBF9oswgTuQoi9/PDS3XRrbZzDJci1hgUVg0awiSJTXkUc3WTHX34sRSCD9QnL+rhcIVctd1cG/hZ8+K3/7gWXwaBZgy2t5vLpB+gv6sqIxlk/BpSuaomQi0CMA9dOUk/o3Wrxa/HCcQSTgHCzCh/9Xpp6C9pOIkeXmvEUbsr+0ihn7Augk3a+sqU1lA7FhcLHC3i/1G/RbJoY3yLu9ox++JmTFB/cEv7wNc3daTkHg18p/i4czsSVJQVa4tgcExo7RFPIhCsTvWEW94EyJzcazCKty+MeNk2ybazX/FyOI7HM8wpdmx2W/aAMzLDh4JqGxuJcedtLKQy4WZMSSsivVdfgz4RQpfUCBIZz75efjAkcgMKFgyL6HPedWbOMAshgWX593K25fPHk9/VJIQ5ToUjrCVhEM06OyeVmu45pFC5y9XGDwxVvtI6rj16OSDeJMiR2DkdYk13hXcoKMVwLbcoD+LcszJ5NVTxplV9h0c3LIkILzf46zcLerrAYq/fb/1gKizM13Txug6lBranXSG4p40Z6V4/i9Y0sNwhK/+AeEvKwBrL4j31GdUJtzo/6yIStXiC5cYENZ3tdQcp0KojDCgHnzJ2+/8oWeREj/nNjo2+8lJXrL3WlilikkoUA+ldHXyBmZZs=
